name: effective_dio_interceptor
description: Simple dio interceptor for logging http requests
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
