name: effective_dio_interceptor
description: Simple dio interceptor for logging http requests
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: ^4.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
